debug: true
network:
  interface: en0
  localhost: localhost
  public_status: true
load_balancer:
  host: localhost
  port: "8090"
  mock: true
machines_local:
  1: 
    host: localhost
    port: "8081"
  2: 
    host: localhost
    port: "8082"
machines_public:
  1: 
    host: "10.250.238.103"
    port: "8081"
  2: 
    host: "10.250.238.103"
    port: "8082"
